# Generated by Django 5.2.8 on 2025-12-04 08:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='n_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='뉴스작성일'),
        ),
    ]
