# Generated by Django 5.2.8 on 2025-12-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.FloatField()),
                ('prd_de', models.IntegerField()),
                ('lst_chn_de', models.DateField()),
                ('c1_nm', models.CharField(max_length=150)),
                ('itm_nm', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': '업종별 재해 사망율 통계',
                'db_table': 't_stats1',
            },
        ),
        migrations.CreateModel(
            name='Stats2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1_obj_nm', models.CharField(max_length=100)),
                ('c2_nm', models.CharField(max_length=20)),
                ('dt', models.FloatField()),
                ('prd_de', models.IntegerField()),
                ('c1_nm', models.CharField(max_length=100)),
                ('itm_nm', models.CharField(max_length=150)),
                ('c2_obj_nm', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '업종별 성별 통계',
                'db_table': 't_stats2',
            },
        ),
        migrations.CreateModel(
            name='Stats3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1_obj_nm', models.CharField(max_length=100)),
                ('c2_nm', models.CharField(max_length=20)),
                ('dt', models.FloatField()),
                ('prd_de', models.IntegerField()),
                ('c1_nm', models.CharField(max_length=100)),
                ('itm_nm', models.CharField(max_length=150)),
                ('c2_obj_nm', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '업종별 성별 사망통계',
                'db_table': 't_stats3',
            },
        ),
        migrations.CreateModel(
            name='Stats4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1_obj_nm', models.CharField(max_length=100)),
                ('c2_nm', models.CharField(max_length=20)),
                ('dt', models.FloatField()),
                ('prd_de', models.IntegerField()),
                ('c1_nm', models.CharField(max_length=100)),
                ('itm_nm', models.CharField(max_length=150)),
                ('c2_obj_nm', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '업종별 연령대 통계',
                'db_table': 't_stats4',
            },
        ),
        migrations.CreateModel(
            name='Stats5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1_obj_nm', models.CharField(max_length=100)),
                ('c2_nm', models.CharField(max_length=20)),
                ('dt', models.FloatField()),
                ('prd_de', models.IntegerField()),
                ('c1_nm', models.CharField(max_length=100)),
                ('itm_nm', models.CharField(max_length=150)),
                ('c2_obj_nm', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '업종별 연령대 사망통계',
                'db_table': 't_stats5',
            },
        ),
        migrations.CreateModel(
            name='Stats6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1_obj_nm', models.CharField(max_length=100)),
                ('c2_nm', models.CharField(max_length=20)),
                ('dt', models.FloatField()),
                ('prd_de', models.IntegerField()),
                ('c1_nm', models.CharField(max_length=100)),
                ('itm_nm', models.CharField(max_length=150)),
                ('c2_obj_nm', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '업종별 발생형태 통계',
                'db_table': 't_stats6',
            },
        ),
        migrations.CreateModel(
            name='Stats7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1_obj_nm', models.CharField(max_length=100)),
                ('c2_nm', models.CharField(max_length=20)),
                ('dt', models.FloatField()),
                ('prd_de', models.IntegerField()),
                ('c1_nm', models.CharField(max_length=100)),
                ('itm_nm', models.CharField(max_length=150)),
                ('c2_obj_nm', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '업종별 발생형태 사망통계',
                'db_table': 't_stats7',
            },
        ),
        migrations.CreateModel(
            name='Stats8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1_obj_nm', models.CharField(max_length=100)),
                ('c2_nm', models.CharField(max_length=20)),
                ('dt', models.FloatField()),
                ('prd_de', models.IntegerField()),
                ('c1_nm', models.CharField(max_length=100)),
                ('itm_nm', models.CharField(max_length=150)),
                ('c2_obj_nm', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '업종별 세부질병 통계',
                'db_table': 't_stats8',
            },
        ),
        migrations.CreateModel(
            name='Stats9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1_obj_nm', models.CharField(max_length=100)),
                ('c2_nm', models.CharField(max_length=20)),
                ('dt', models.FloatField()),
                ('prd_de', models.IntegerField()),
                ('c1_nm', models.CharField(max_length=100)),
                ('itm_nm', models.CharField(max_length=150)),
                ('c2_obj_nm', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '업종별 세부질병 사망통계',
                'db_table': 't_stats9',
            },
        ),
    ]
