# Generated by Django 5.2.8 on 2025-12-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_contents', models.TextField(verbose_name='리뷰내용')),
                ('r_created_at', models.DateTimeField(auto_now_add=True, verbose_name='리뷰작성일')),
                ('r_rating', models.IntegerField(verbose_name='평점')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hospital.hospital', verbose_name='리뷰가 작성된 병원')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='member.member', verbose_name='리뷰 작성한 회원')),
            ],
            options={
                'verbose_name': '병원 리뷰',
                'verbose_name_plural': '병원 리뷰 목록',
                'db_table': 't_review',
            },
        ),
    ]
