# Generated by Django 5.2.8 on 2025-12-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=150, verbose_name='안전 자료 제목')),
                ('s_image_url', models.CharField(max_length=1000, verbose_name='안전 자료 이미지 url')),
                ('s_type', models.CharField(max_length=10, verbose_name='안전 자료 형태')),
                ('s_contents', models.CharField(max_length=500, verbose_name='안전 자료 내용')),
                ('s_view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('s_created_at', models.DateTimeField(auto_now_add=True, verbose_name='안전 자료 작성일')),
                ('s_publisher', models.CharField(default='KOSHA', max_length=100, verbose_name='자료 출처명')),
                ('s_link', models.CharField(max_length=1000, verbose_name='안전 상세페이지 링크')),
                ('s_video_url', models.CharField(max_length=1000, null=True, verbose_name='안전 자료 동영상 url')),
            ],
            options={
                'verbose_name': '안전 자료',
                'verbose_name_plural': '안전 자료 목록',
                'db_table': 't_safe',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_tag', models.CharField(max_length=100, unique=True, verbose_name='태그명')),
            ],
            options={
                'verbose_name': '안전자료실 태그',
                'verbose_name_plural': '안전자료실 태그(들)',
                'db_table': 't_tag',
            },
        ),
        migrations.CreateModel(
            name='SafeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe.safe')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe.tag')),
            ],
            options={
                'verbose_name': '안전자료실 태그 연결',
                'verbose_name_plural': '안전자료실 태그 연결 목록',
                'db_table': 't_safe_tag',
            },
        ),
        migrations.AddField(
            model_name='safe',
            name='tags',
            field=models.ManyToManyField(through='safe.SafeTag', to='safe.tag', verbose_name='태그'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_vdate', models.DateTimeField(auto_now_add=True, verbose_name='방문일시')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member', verbose_name='회원번호')),
                ('safe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safe.safe', verbose_name='안전자료 번호')),
            ],
            options={
                'verbose_name': '안전자료 방문기록',
                'verbose_name_plural': '안전자료 방문기록(들)',
                'db_table': 't_history',
                'ordering': ['-h_vdate'],
                'constraints': [models.UniqueConstraint(fields=('member', 'safe'), name='unique_member_safe')],
            },
        ),
    ]
