# Generated by Django 5.2.8 on 2025-12-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_hospital_name', models.CharField(max_length=100, verbose_name='의료기관명')),
                ('h_address', models.CharField(max_length=150, verbose_name='소재지')),
                ('h_phone_number', models.CharField(max_length=11, verbose_name='전화번호')),
                ('h_hospital_type', models.CharField(max_length=100, verbose_name='종별')),
                ('h_rc', models.CharField(max_length=100, null=True, verbose_name='부가기능(재활인증, 진폐요양)')),
                ('h_rc_info', models.CharField(max_length=100, null=True, verbose_name='재활인증(만료일)')),
                ('h_tr', models.CharField(max_length=100, null=True, verbose_name='진료제한(기간)')),
                ('h_ei', models.CharField(max_length=100, null=True, verbose_name='의료기관평가(평가연도)')),
            ],
            options={
                'verbose_name': '산재지정병원',
                'verbose_name_plural': '산재지정병원 목록',
                'db_table': 't_hospital',
            },
        ),
    ]
