# Generated by Django 5.2.8 on 2025-12-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='h_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='h_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
