# Generated by Django 5.2.8 on 2025-12-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_sex', models.CharField(max_length=6, verbose_name='성')),
                ('m_birth_date', models.DateField(verbose_name='생년월일')),
                ('m_name', models.CharField(max_length=100, verbose_name='이름')),
                ('m_username', models.CharField(max_length=100, unique=True, verbose_name='회원 아이디')),
                ('m_password', models.CharField(max_length=300, verbose_name='회원 비밀번호')),
                ('m_phone', models.CharField(max_length=11, null=True, verbose_name='회원 전화번호')),
                ('m_address', models.CharField(max_length=150, verbose_name='회원 거주지 주소')),
                ('m_jaddress', models.CharField(max_length=150, verbose_name='회원 근무지 주소')),
                ('m_email', models.EmailField(max_length=100, null=True, verbose_name='회원 이메일')),
                ('m_provider', models.CharField(max_length=100, verbose_name='oauth 제공자')),
                ('m_provider_id', models.CharField(max_length=100, verbose_name='oauth 아이디')),
                ('m_address_lat', models.FloatField(verbose_name='거주지 위도')),
                ('m_address_lng', models.FloatField(verbose_name='거주지 경도')),
                ('m_jaddress_lat', models.FloatField(verbose_name='근무지 위도')),
                ('m_jaddress_lng', models.FloatField(verbose_name='근무지 위도')),
                ('m_created_at', models.DateTimeField(auto_now_add=True, verbose_name='회원 가입일')),
                ('m_status', models.IntegerField(choices=[(0, '관리자'), (1, '멤버'), (99, '탈퇴자')], default=1, verbose_name='회원 상태')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자(들)',
                'db_table': 't_member',
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_accident_date', models.DateField(null=True, verbose_name='재해일자')),
                ('i_injury', models.CharField(max_length=100, null=True, verbose_name='발생형태')),
                ('i_disease_type', models.CharField(max_length=100, null=True, verbose_name='질병')),
                ('i_address', models.CharField(max_length=150, verbose_name='발생주소')),
                ('i_address_lat', models.FloatField(verbose_name='발생지 위도')),
                ('i_address_lng', models.FloatField(verbose_name='발생지 경도')),
                ('i_title', models.CharField(max_length=10, verbose_name='산재제목')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individuals', to='member.member', verbose_name='회원')),
            ],
            options={
                'verbose_name': '개인산재정보',
                'verbose_name_plural': '산재정보(들)',
                'db_table': 't_individual',
            },
        ),
        migrations.CreateModel(
            name='Member_industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_industry_type1', models.CharField(max_length=50, verbose_name='업종중분류1')),
                ('i_industry_type2', models.CharField(max_length=50, verbose_name='업종중분류2')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='member.member', verbose_name='회원')),
            ],
            options={
                'verbose_name': '회원 업종 테이블',
                'verbose_name_plural': '업종(들)',
                'db_table': 't_member_industry',
            },
        ),
    ]
