# Generated by Django 5.2.8 on 2025-12-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='m_provider',
            field=models.CharField(default='local', max_length=100, null=True, verbose_name='oauth 제공자'),
        ),
    ]
