# Generated by Django 5.2.8 on 2025-12-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='m_provider',
            field=models.CharField(max_length=100, null=True, verbose_name='oauth 제공자'),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_provider_id',
            field=models.CharField(max_length=100, null=True, verbose_name='oauth 아이디'),
        ),
    ]
