# Generated by Django 5.2.8 on 2025-12-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_m_provider_alter_member_m_provider_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='m_address_lat',
            field=models.FloatField(null=True, verbose_name='거주지 위도'),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_address_lng',
            field=models.FloatField(null=True, verbose_name='거주지 경도'),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_jaddress_lat',
            field=models.FloatField(null=True, verbose_name='근무지 위도'),
        ),
        migrations.AlterField(
            model_name='member',
            name='m_jaddress_lng',
            field=models.FloatField(null=True, verbose_name='근무지 위도'),
        ),
    ]
