# Generated by Django 5.2.8 on 2025-12-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_m_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='m_sex',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=6, verbose_name='성'),
        ),
    ]
